### ISSUE TITLE
doesn't show code blocks

### ISSUE THREAD

**Issue by millerthegorilla** [rNeomy/reader-view#10]
Hi, I am using reader view at the moment and it is great - thanks!

However, it doesn't include [code][/code] blocks from some sites, such as the following:
https://www.techyourchance.com/liskov-substitution-principle/

I'd be grateful if this could occur - it would be really helpful.  Thanks.

**Comment by rNeomy** [comment]
Since the code blocks are not being shown in Firefox too (with the official readability library), please report this to https://github.com/mozilla/readability

This extension uses the "readability" library but is not going to modify the original code.
