### ISSUE TITLE
Please support WeChat article's images

### ISSUE THREAD

**Issue by VimWei** [rNeomy/reader-view#104]
example: https://mp.weixin.qq.com/s/zS-UEK24DFTTIggL90JK4A

We can open this page in chrome with normal images display.
And we can use another chrome extention "reader mode" to open this page.

But when I use reader-view，all the images in this page can't display.

**Comment by rNeomy** [comment]
This extension by default does not have permission to read remote content, that is why loading of any remote content fails. Go to the options page of the extension and check the "Open links in the reader view mode" option. This permission allows the extension to have access to remote content (this is for another purpose though!). Restart your browser or the Reader View extension and images should load just fine.

**Comment by VimWei** [comment]
Thanks! It works!
