### ISSUE TITLE
Feature Request: Dyslexie Font

### ISSUE THREAD

**Issue by RadekPilich** [rNeomy/reader-view#11]
I would love to see a dyslexie font included besides currently present serif and sans-serif fonts.
https://www.dyslexiefont.com

**Comment by rNeomy** [comment]
Have you tried the custom styling method? FAQS5? https://add0n.com/chrome-reader-view.html

Note that this only works in Chrome and Opera.

**Comment by RadekPilich** [comment]
Brilliant. Thank you!
