### ISSUE TITLE
`User Action`s blocked by Firefox's Content Security Policy

### ISSUE THREAD

**Issue by pcdi** [rNeomy/reader-view#117]
# Problem
User actions seem to be blocked by Firefox's [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy).
```
Reader View Version 0.5.1
Firefox Version 91.3.0esr (64-Bit)
OS Windows 10 Enterprise 20H2 19042.1348
```

# How to reproduce:
- In the settings page, under _User Actions_, paste the [sample button from the FAQ](https://add0n.com/chrome-reader-view.html#faq16):
```json
[{
  "code": "console.log('User Click')",
  "title": "Sample Button",
  "shortcut": "Ctrl/Command + Shift + KeyL"
}]
```
- Visit a website and activate _Reader View_
- Click the new button for the user action
- In the dev console, the following errors appear:
> Loading failed for the <script> with source  "blob:moz-extension://HASH". 
> Content Security Policy: The page’s settings blocked the loading of a resource at blob:moz-extension://HASH ("[script-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src)").

**Comment by rNeomy** [comment]
Thanks for the report.

**Comment by kestoske** [comment]
Hi. Could you release those changes to https://addons.mozilla.org?

**Comment by rNeomy** [comment]
@kestoske the 0.5.1 release is already in AMO. Do you still have the issue? If so please provide an example.

**Comment by kestoske** [comment]
Thanks, it works now.
