### ISSUE TITLE
cmd === 'font-increase': Could you please allow bigger fonts?

### ISSUE THREAD

**Issue by schittli** [rNeomy/reader-view#12]
Hello
Thank you very much for this useful extension!, 
could you please allow us to use bigger fonts if we use the font-increase command?

The older we get, the bigger the font :-)

Thanks a lot, kind regards,
Thomas

**Comment by rNeomy** [comment]
The new version accepts up to 33px. For larger `font-size` use the options page to inject a custom CSS rule. You will need to adjust `line-height` as well. Read more here https://add0n.com/chrome-reader-view.html#faq5

**Comment by schittli** [comment]
Thanks a lot!!, very useful :-)
