### ISSUE TITLE
What is `data-mode`?

### ISSUE THREAD

**Issue by arandorion** [rNeomy/reader-view#124]
What is `data-mode`? I've seen it referenced in the CSS, but I have no idea what it is or why it's being used?

Thanks

**Comment by rNeomy** [comment]
https://github.com/rNeomy/reader-view/blob/3747d85a74397195a9fd64a823898cbcac9ea7ed/WebExtension/firefox/data/reader/index.css#L48-L79

Let the CSS know what is the used theme.

**Comment by arandorion** [comment]
Ah, so you can use it to target specific themes. Cool.

Thanks for the info!
