### ISSUE TITLE
Wrong position of image resizer in Design Mode

### ISSUE THREAD

**Issue by kestoske** [rNeomy/reader-view#127]
[Span element](https://github.com/rNeomy/reader-view/blob/ee4bfb4d8272a9169b84f64c5ab21e1ac8c0a239/WebExtension/firefox/data/reader/libs/design-mode/inject.js#L20) of image resizer appears in the wrong place after `body` position has been changed to "[relative](https://github.com/rNeomy/reader-view/blob/ee4bfb4d8272a9169b84f64c5ab21e1ac8c0a239/WebExtension/firefox/data/reader/template.html#L15)".

**Comment by rNeomy** [comment]
Thanks for the report. It is fixed.
