### ISSUE TITLE
Link opened in a new tab by command/control-clicking open in reader view

### ISSUE THREAD

**Issue by elcste** [rNeomy/reader-view#143]
Using Reader View 0.6.3 on Chrome 105.0.5195.125 on Mac and I have **Open links in the reader view mode** unchecked

I'm seeing that links opened in a new tab by command-clicking the link (same as control-clicking on Windows/Linux) open in Reader View. If I right click and choose to open in a new tab, it does not open in Reader View, and clicking a link without any modifiers in the same tab also does not open Reader View.

**Comment by rNeomy** [comment]
Thanks for the report. Will get fixed by the next release.
