### ISSUE TITLE
[Issue] Watson voices doesn't work

### ISSUE THREAD

**Issue by Jonhy75** [rNeomy/reader-view#148]
Hello,

Watson voices doesn't work since few week.
Tested with french, spanish and english voices.
I'm using Brave 1.44.112

**Comment by longskatedeath** [comment]
Hi, just to add another, related issue:
Selecting the "Google UK English Female" voice switches to "Google UK English Male". Unfortunately, it doesn't do the opposite when choosing the male voice.

**Comment by rNeomy** [comment]
@longskatedeath I can reproduce this. It seems like a Chrome bug. I'll investigate more.
