### ISSUE TITLE
Invalid DOM traversal with CustomElements

### ISSUE THREAD

**Issue by avoidwork** [rNeomy/reader-view#15]
Hi,

Your chrome reader view addon causes a bug on https://guided.adobe.com due to my use of CustomElement for web components with https://github.com/mikeal/gza which one of my coworkers bumped into.

Somewhere you have a hard coded DOM path that needs to become aware of Shadow DOM.

**Comment by rNeomy** [comment]
You mean even in the normal mode? I am not following as I dont get any error when the extension is installed.

**Comment by avoidwork** [comment]
I have an unrelated network issue with google that's blocking installing it on my device (I can't verify if it's an issue or not), so I'm happy saying the issue is a composition of a few things on said laptop of my coworker.
