### ISSUE TITLE
Can you add export of markdown format files?

### ISSUE THREAD

**Issue by zhl111** [rNeomy/reader-view#154]
Really like your plugin and hope it's better
ex. - [theowenyoung/markdownload: A Firefox and Google Chrome extension to clip websites and download them into a readable markdown file.](https://github.com/theowenyoung/markdownload#readme )  2022/12/1
It would be nice to have a custom directory for the saved files

**Comment by rNeomy** [comment]
You can try the developer version:

1. Open "chrome://extensions/" in a browser tab
2. Turn the developer mode on
3. Download the project from https://github.com/rNeomy/reader-view/archive/refs/heads/master.zip
4. Extract it into a local directory
5. Drop the "v3" directory into the "chrome://extensions/" view

**Comment by rNeomy** [comment]
> the saved file does not have a file extension.

What is your browser? For me, it saves in "*.markdown". I'll change it into "*.md" for production.

> The saved files can be selected to other folders. 

You can temporarily change the default download directory of your browser to save in the desired directory. The extension cannot access any local disk, so we can not have a custom save directory for this extension.
