### ISSUE TITLE
Watson voice 

### ISSUE THREAD

**Issue by hrj-br** [rNeomy/reader-view#167]
Thanks for fantastic job with extension. 

One best feature is read aloud with Watson voice, but it is not working any more, or inconsistently working. 
Any fix to come?

**Comment by hackerb9** [comment]
I can confirm that this is a problem. I'm using version 0.6.9 under Firefox.

**Comment by GitCntb** [comment]
Noticed the following in extension properties:
![capture](https://user-images.githubusercontent.com/128921290/227729649-4c37125e-2406-4f62-8648-63fc3138590e.png)

Then tried to access Watson Demo webpage in Firefox and received the following message:
**404 Not Found: Requested route ('speech-to-text-demo.ng.bluemix.net') does not exist.**

After searching, the new Watson Demo webpage address is this:
**https://www.ibm.com/demos/live/tts-demo/self-service/home**

Hope this can help in any way.
Thanks again for the excellent work in this extension.

**Comment by Marc-Gee** [comment]
I support this bugfix please. the watson english voice is the one one that seems to read correctly. Microsoft voices read badly and make "is" as "eye es " or "i.s."  somehow!!!

**Comment by rNeomy** [comment]
I am going to remove the Watson voices. The demo only plays a few line.

**Comment by rNeomy** [comment]
Watson voices on the demo page only work for a few lines. Then you get 500 server error even on the official demo page. So there are not suitable for production use.

**Comment by Marc-Gee** [comment]
Ah, that's a pity. However, thanks for trying.


________________________________
