### ISSUE TITLE
For ChatGPT, Clearly Reader extension formats the entire page, but Reader View only works on the last prompt

### ISSUE THREAD

**Issue by JeffKang** [rNeomy/reader-view#199]
Hi there, the two reading extensions that I find to be the best are Reader View and Clearly Reader.

I prefer Reader View because you can format the page like a newspaper with up to 4 columns. The content takes up most of the window width, so there's less wasted white space

It's comparable to Microsoft Word > View > Read Mode > View > Layout > Column Layout

For ChatGPT though, Reader View only seems to format the last prompt If you have a page of multiple prompts.

Clearly Reader works fine on the entire page.

Is this a limitation of Reader View’s design, or just something that hasn't been looked into yet.

Cheers,

**Comment by rNeomy** [comment]
The "Readability.js" library only parses the last article on the page. From the next release, the extension parses all articles and places each in a new page section. You can give the latest commit a try.

**Comment by JeffKang** [comment]
Thanks a lot, rNeomy.
