### ISSUE TITLE
<html lang="language" attribute Missing after using. 

### ISSUE THREAD

**Issue by HornyPrivateGamer** [rNeomy/reader-view#201]
That  i tried to change 

/* Green background for English */
:lang(en) {
  background-color: green !important;
}

/* Green background for Japanese */
:lang(ja) {
  background-color: green !important;
}

that both didnt work as  lang="language" attribute Missing after enabling the exntesion.

**Comment by HornyPrivateGamer** [comment]
@rNeomy Please help thanks. 
I don't know why this is not working.
That i tested what you can only change the CSS lanuage for EN

**Comment by HornyPrivateGamer** [comment]
The only website that is working is 
https://en.wikipedia.org/wiki/Deutschland_sucht_den_Superstar

using the code 

:lang(EN), :lang(FR) {
  color: blue !important;
}

**Comment by HornyPrivateGamer** [comment]
Could any Pro could me why this is the case please
begging right now.

**Comment by rNeomy** [comment]
The extension did not set the `lang` attribute. This will work from the next release.

![Screenshot](https://github.com/user-attachments/assets/809e5cfb-3229-4812-841d-36c7945b0e69)

**Comment by HornyPrivateGamer** [comment]
> The extension did not set the `lang` attribute. This will work from the next release.
> 
> ![Screenshot](https://private-user-images.githubusercontent.com/14104614/383835377-809e5cfb-3229-4812-841d-36c7945b0e69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjI2NjQsIm5iZiI6MTczMDk2MjM2NCwicGF0aCI6Ii8xNDEwNDYxNC8zODM4MzUzNzctODA5ZTVjZmItMzIyOS00ODEyLTg0MWQtMzZjNzk0NWIwZTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA2NTI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NDExZDc4OTQxMGYzNjgzYzg4YjAyNzViZTYwOWNjZmI1YTlmNmJmNTc3YzBlYTU2YTY3Y2U5YWRiMGIxZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0EjuqR_6fwBWapUHwjtDZ_Hbgvcypny9eg1iPNVAXnc)

ok thanks a lot sir any way i can Donte  you .

**Comment by rNeomy** [comment]
You can use the donation links on the homepage; https://webextension.org/listing/chrome-reader-view.html
