### ISSUE TITLE
add ability to request access to one site not to give access to all sites. for "automatic switch" option

### ISSUE THREAD

**Issue by arkarkark** [rNeomy/reader-view#203]
It appears I need to give access to all sites to turn on the "Automatic Switch" option. 

The [scrollmaps](https://chromewebstore.google.com/detail/scrollmaps/jifommjndpnefcfplgnbhabocomgdjjg?pli=1) extension manages this in a different way, The extension is able to request access to just the current page's site and then it can run automatically on that site.

o.k. I just played with it and I got it to allow me to only grant access to one site `https://www.californiasun.co/` by granting access to all, then updating the 'automatic switch' value to `californiasun.co` then restarting the extension, but when I go to 
the [https://www.californiasun.co/](https://www.californiasun.co/) reader does not automatically turn on. But I am able to right click on the reader icon and select "This Can Read and Change Site Data" for just the site I'm on. I can only seem to edit the "automatic switch" value when I have granted all sites access.

thoughts to make it batter

1. I think I'd suggest allowing you to edit Automatic switch values all the time
2. Also change the "request access" label to "request access on all sites"
3. provide some way to request access to just the current site
4. tell me what I'm doing wrong to actually make it automatically turn on when I open a page that matches what's in my "automatic switch" value.

**Comment by rNeomy** [comment]
As of the next release, a button for limited host access will be available. You can create a list of hostnames and confirm it. To test the interface, install the latest commit.

> Please let me know what I'm doing wrong that causes it to automatically activate when I open a page matching my "automatic switch" value.

Ensure that you include `www.californiasun.co` in your list, rather than just `californiasun.co`.

**Comment by arkarkark** [comment]
confirmed this works by loading the v3 as an unpacked extension. thanks so much!
