### ISSUE TITLE
Increase the maximum font size allowed

### ISSUE THREAD

**Issue by dreais** [rNeomy/reader-view#204]
https://github.com/rNeomy/reader-view/blob/4aaa26a80227c21cc086079bff68646e208bd9fc/v3/data/reader/index.js#L609

I have a (pretty) big screen and when I read I like to kind of set myself back, so I usually use a font size around 60. Could the maximum font size be increased to 80 (just in case)? 

I'm using a modified extension for the time being (not distributed), so nothing urgent, but would be nice.

**Comment by rNeomy** [comment]
Done! thanks for the suggestion.
