### ISSUE TITLE
Options to do automatic full screen mode in reader view

### ISSUE THREAD

**Issue by anishmittal2020** [rNeomy/reader-view#22]
In chrome extension, I request you to provide option if the user wants the reader view in full screen. 

This supports the philosophy behind to avoid clutter and be able to focus.

**Comment by rNeomy** [comment]
We will have the button in the left-side panel. Thanks for the suggestion.

**Comment by anishmittal2020** [comment]
I don't recommend another button as we already know keyboard shortcut for full sctrrn F9. It would be more suited as an option, and if the user opts for it, it could directly become full screen in reader mode.

**Comment by rNeomy** [comment]
> I don't recommend another button as we already know keyboard shortcut for full sctrrn F9

as you may know this is a Windows only shortcut. We now have options to hide and show buttons in the options page. btw, most of the buttons now have shortcuts.

**Comment by anishmittal2020** [comment]
Hi, I think I was not very clear. I was not implying that we need a button. What I meant is that people use this extension to remove clutter from the webpage. Some people might like to go to the full-screen mode directly when they click this extension on any webpage. I was asking about giving an option for opening the webpage in full screen by default. To those who don't want this may not select this option.

**Comment by rNeomy** [comment]
I added an option for this, but it is not going to be equal to the button we have in the UI (window fullscreen vs tab fullscreen). There is no way to accomplish it. Some APIs only work when there is a user-action involved.
