### ISSUE TITLE
Please add TTS  options to GUI

### ISSUE THREAD

**Issue by sssem** [rNeomy/reader-view#23]
Please add TTS  controlls:
◀ restart current / go to the Previous paragraph
▲/▼ Speed up/down (I know it's in options, but different articles need different speeds)
▲/▼ Volume up/down (just to be awesome ;) )

Keep up the great job, yours is the only reading view for chrome that rivals to firefox's!!!!

THANK YOU!!

**Comment by rNeomy** [comment]
![screen shot](https://user-images.githubusercontent.com/14104614/48399083-9339ba00-e71a-11e8-8a5d-496c36da50a5.png)

Note that the TTS implementation is really buggy and platform dependent. I prefer not to add options if they are not really necessary.

> restart current / go to the Previous paragraph

added (still in the beta phase)

> Speed up/down

I think this clutters the UI and most keyboards already have the volume controls on them (you can still work on this and submit a pull request).

> Speed up/down

added (still in the beta phase)
