### ISSUE TITLE
[Feature request] Overlay page instead of loading a new one

### ISSUE THREAD

**Issue by marnovo** [rNeomy/reader-view#24]
In a similar fashion to most reader extensions like [DOM Distiller](https://chrome.google.com/webstore/detail/dom-distiller-reading-mod/oiembdaoobijmdmeobkalaehgifealpl) and [Reader View](https://chrome.google.com/webstore/detail/reader-view/ecabifbgmdmgdllomnfinbmaellmclnh), show the transformed/simplified text without leaving the page to an extension one. Often you lose the original page once you reload it back, if it's updated or somewhat dynamic. Also doesn't work well with tab suspenders and the alike.

Also would solve: https://github.com/rNeomy/reader-view/issues/6

**Comment by rNeomy** [comment]
Is it not a good idea, performance and memory-wise, to have the original dom accessible meaning the original scripts are still active even if the dom elements are removed. This method does not prevent tracking script and ad scripts from being cleared from the dom object.
