### ISSUE TITLE
Allow setting background and forefront color

### ISSUE THREAD

**Issue by dalvarezsmiet** [rNeomy/reader-view#3]
It is nice to have this "only-read" view, but I would like to be able to setup the background color. Sometimes I can prefer it to be white, while others it would be great to have a darker one (black or else) with lighter font.

Is that possible?

Let me know if I can collaborate in this, please.

**Comment by rNeomy** [comment]
Is this for Firefox or Chrome?

**Comment by dalvarezsmiet** [comment]
I was thinking in Firefox, because I use it more, but I guess if this can be done once in a browser, then it could/should be ported to the other one.

**Comment by rNeomy** [comment]
Firefox already has three color schemes
![screen shot 2017-01-30 at 19 00 55](https://cloud.githubusercontent.com/assets/14104614/22429096/b7758eec-e71e-11e6-8907-5310b7f3e841.png)

**Comment by dalvarezsmiet** [comment]
Sorry, I didn't see that. I noticed this is also implemented in Opera. Very good! Thanks
