### ISSUE TITLE
Design Flaw: While using touchpad to scroll the text moves sideways also

### ISSUE THREAD

**Issue by anishmittal2020** [rNeomy/reader-view#31]
Using touchpad is a more fluid way to scroll the page.  When I try to do it, then because my motion of finger is not precisely straight the text also shifts sideways, which is undesirable.

Please fix this issue, as to make the functionality more useful.

**Comment by rNeomy** [comment]
> the text also shifts sideways

I don't experience this. Can you provide an example page with this issue.
