### ISSUE TITLE
Add padding to reading area for Mac OS' smart zoom 

### ISSUE THREAD

**Issue by ftkurt** [rNeomy/reader-view#32]
Smart zoom on Mac OS enables you to zoom to the reading area. However read mode in the extension has a reading area with no padding. Therefore, when zoomed, text will have no padding to the sides of the screen. Widening reading area and adding the same amount of padding to the div element would make no visible difference, but would fix the problem with smart zoom.

**Comment by rNeomy** [comment]
Just add the following code to the user-style section of the add-on;

```css
p {padding: 0 10px;}
```
