### ISSUE TITLE
The images are scaling incorrectly

### ISSUE THREAD

**Issue by stasukas** [rNeomy/reader-view#33]
If a page contains hi-res images the addon doesn't scale it at all. I see that the body tag have width style modificator but the img tags have no scaling styles.

Just add this style to default styling in reader mode
```
img {
  max-width: 90%;
  height: auto;
}
```

You can test this issue at page http://www.mobile-review.com/articles/2019/samsung-unpacked-2019.shtml

**Comment by rNeomy** [comment]
Thanks! I am using your code with `max-width: 100%;`. Looks good to me.
