### ISSUE TITLE
Unable to override font-size with CSS

### ISSUE THREAD

**Issue by dearestleader** [rNeomy/reader-view#35]
Used sample code from https://add0n.com/chrome-reader-view.html
Added the italic, font-size, and font-family attributes. When switching between dark, sepia,  and white, I see the red text and font style italic, but the size and font family are not changed. It doesn't appear possible to override the -+ buttons on the Aa tab.
body[data-mode=dark] {
  color: red !important;
font-family: "Times New Roman", Times, serif;
  font-size: xx-large;
font-style: italic;

**Comment by rNeomy** [comment]
Thanks for the report. Should have been fixed by https://github.com/rNeomy/reader-view/commit/be6d69f2c11f8273c06fcb6d24304c778ee13d3b

**Comment by sergeevabc** [comment]
Err… How do I set different custom fonts for sans ans serif options to switch them on-the-fly?
With default FF Reader it is possible via userContent.css as follows
```
@-moz-document url-prefix("about:reader") {
  body.sans-serif {
    font-family: "Ubuntu", sans-serif !important;
  }
  body.serif {
    font-family: "Alegreya", serif !important;
  }
}
```
