### ISSUE TITLE
Custom CSS pre{white-space: pre-line;} breaks indented code blocks

### ISSUE THREAD

**Issue by jimbo1qaz** [rNeomy/reader-view#38]
The default "Custom CSS" sets `pre` tags to `white-space: pre-line`.

https://github.com/rNeomy/reader-view/blob/1f851762fbae4991756dfdba177c057fa261c668/WebExtension/firefox/common.js#L220-L222

This causes \<pre\> code to lose indentation, and instead all lines start at the left margin.

I think you should remove that part of the custom CSS (or change to `pre-wrap`? https://developer.mozilla.org/en-US/docs/Web/CSS/white-space )

**Comment by rNeomy** [comment]
`pre-wrap` it is. Thanks!
