### ISSUE TITLE
Opera version 60 extension not in the url bar

### ISSUE THREAD

**Issue by federicorosso** [rNeomy/reader-view#39]
With Opera version 59 the Reader extension was in the url bar, with Opera 60 it is now with other extensions. I liked the way it was before, can you do anything about it or it's an Opera v 60 limitation?

Thank you.

**Comment by rNeomy** [comment]
Unfortunately, the position where the page-action button is located solely determines by your browser. There is no option to set the position. Seems like you cannot have "any" extension in the address bar anymore.
