### ISSUE TITLE
Google News redirects do not work

### ISSUE THREAD

**Issue by TimMagee** [rNeomy/reader-view#4]
While links from Google redirect correctly, links from Google News do not making this extension nearly useless to me.

**Comment by rNeomy** [comment]
Is this on Firefox?

**Comment by TimMagee** [comment]
Yes, this is on Firefox.

**Comment by rNeomy** [comment]
Can you share a link. Right-click over a link that is not being redirected correctly and copy it into the clipboard.

**Comment by TimMagee** [comment]
https://news.google.com/articles/CBMiPWh0dHBzOi8vd3d3LmludmVzdG9ycy5jb20vbmV3cy90ZWNobm9sb2d5L3VzLWNoaW5hLXRyYWRlLXdhci_SAQA?hl=en-US&gl=US&ceid=US%3Aen

**Comment by rNeomy** [comment]
Thanks! It should be fixed on the next release. Reopen if not.

**Comment by TimMagee** [comment]
Awesome! Thank you!
