### ISSUE TITLE
Allow resizing of images in reader view

### ISSUE THREAD

**Issue by aspgh** [rNeomy/reader-view#40]
Hello,

Maybe it wasn't Readable, but I recall one add-on that allowed **scaling the images to a smaller or larger size in the Reader View.** I hope you can also implement this. Thank you very much.

**Comment by rNeomy** [comment]
You mean by having a small resize icon next to the image? https://www.w3schools.com/cssref/tryit.asp?filename=trycss3_resize

**Comment by aspgh** [comment]
Hi, and thanks for the prompt reply.

I haven't thought of this possibility, but this is in fact useful because the user can resize the image to the preferred size. However, it might be tedious if there are many images in the page that the user would want to resize, because in this case the user would have to adjust the images one by one.

The possibility that I was thinking of was some sort of slider (or '+/-' buttons, like the ones for adjusting the font size), which would resize all the images in the page by a common factor. This would be especially useful for the reader for pages where the images are either too big or too small, and therefore would be a discomfort for reading (as well as printing).

Or perhaps both things can be implemented: (1) a common-factor resizing for all images, and (2) the possibility of manual resizing for individual images, in case there is a (perhaps rare) mix of images-- in the exact same page-- that are too big and too small.

Thank you very much, and best regards.

**Comment by rNeomy** [comment]
We are going to have this on the next release;
![img](https://user-images.githubusercontent.com/14104614/58366677-5e769e80-7ec5-11e9-80b0-f1fdae05e5c4.png)

Thanks for the feature request!
