### ISSUE TITLE
Custom themes: Solarized Dark and Light Theme

### ISSUE THREAD

**Issue by anishmittal2020** [rNeomy/reader-view#45]
Dark mode has high contrast with white text on black background. It would be good to use eye friendly themes like Solarized Dark and Light. Also, if possible please support custom themes.

**Comment by anishmittal2020** [comment]
@rNeomy The solarized colour you have chosen is  as follows:

![image](https://user-images.githubusercontent.com/42092626/137359393-987e6ce2-1927-49b0-92d3-56b286bdbf6e.png)

But the solarized dark theme as intended should have this pair of color:

| Description          | Background       | Foreground       |
| :------------------- | :--------------- | :--------------- |
| Main Body            | `#002b36` Base03 | `#839496` Base0  |
| Emphasis (Important) | `#073642` Base02 | `#93a1a1` Base1  |
| Comments (Lighter)   | `#002b36` Base03 | `#586e75` Base01 |

Please, swap `#93a1a1` with `#839496` for the right contrast ratio.

**Comment by anishmittal2020** [comment]
@rNeomy Any update?

**Comment by rNeomy** [comment]
done
