### ISSUE TITLE
Style correction

### ISSUE THREAD

**Issue by snilek** [rNeomy/reader-view#5]
To work properly with images and for ergonomic reading of the end of the text, the following needs to be added as custom CSS.
<pre>img {
  display: block;
  max-width: 100%;
  width: auto;
  height: auto;
}
body {
  padding-bottom: 5em;
}</pre>

I would suggest to add this (or some variant of) to the codebase.

Just to note, I am using the Opera version, where the extension got a recent update. This codebase seems to be old(er) though?

Thanks for a working reader-view extension,
Jan Jansky

**Comment by rNeomy** [comment]
Thanks! The new version will insert this CSS code by default

**Comment by snilek** [comment]
And probably the CSS for `img` should be applied to `iframe` also, Some iframes tend to exceed the text width.

**Comment by rNeomy** [comment]
Can you provide a sample link?

**Comment by snilek** [comment]
[Here for example...](https://www.rt.com/news/398782-france-terrorism-knife-attack-eiffel-tower/)
