### ISSUE TITLE
custom styling

### ISSUE THREAD

**Issue by ab529p** [rNeomy/reader-view#56]
Hi, pls tell me how can i achieve the followings

1. move the side menu to either top or bottom

2. change both background and font color

thanks

**Comment by ab529p** [comment]
2. change both background and font color

- got this one figured out
body[data-mode=dark] {
  background-color: #1c1911;
  color: grey;
}

**Comment by ab529p** [comment]
@rNeomy , Would appreciate some help on 
1. move the side menu to either top or bottom

thanks

**Comment by rNeomy** [comment]
> move the side menu to either top or bottom

Check this new FAQ; https://add0n.com/chrome-reader-view.html?nc#faq14
