### ISSUE TITLE
Keep page URL in address bar

### ISSUE THREAD

**Issue by snilek** [rNeomy/reader-view#6]
When in reader-view mode, the address bar (at least in Opera) is blank. The URL is in the domain link on top of the page, but it would be better to keep/add it to the browser address bar also.

Thanks,
Jan Jansky

**Comment by jefferyyuan** [comment]
👍 for this feature.
- when we are reading this page in reader view, sometimes, we want to copy the URL (for various reason).
- now we have to press Esc, chrome will reload the page, then open the page in reader view mode again.
- This looks like a waste of system resource. : )

**Comment by datocrats-org** [comment]
this feature would also enable me to use tools like [hypothesis ](https://hypothes.is/) to annotate the content in reader mode - it requires the URL be there in order to wrap content in annotations (highlights)

**Comment by rNeomy** [comment]
> now we have to press Esc, chrome will reload the page, then open the page in reader view mode again.

Right click on the title of an article and copy the link.

**Comment by rNeomy** [comment]
> this feature would also enable me to use tools like hypothesis to annotate the content in reader mode

It simply is not doable. No external script is allowed to be injected into local pages. Even if this script could somehow be injected, it cannot communicate with its server. We are going to have a simple highlighter as of the next release for basic usage.

**Comment by alex-rozenshteyn-leapyear** [comment]
Would it be possible to have a version of this extension as a bookmarklet (or otherwise to modify the current page's dom rather than open a new one)? For example, like https://ejucovy.github.io/readability/ ?

**Comment by rNeomy** [comment]
We are going to have a new "Simple Mode" which is accessed from the right-click context menu over the page action's button. In this mode, the extension writes the reader view directly on the DOM so the URL is kept. However, since there is a need to replace the existing node, some of the existing scripts of the page may not function correctly. Also, note that this mode is not unloading the page scripts so don't expect the page to be lighter in the reader view.

**Comment by alex-rozenshteyn-leapyear** [comment]
> We are going to have a new "Simple Mode" which is accessed from the right-click context menu over the page action's button.

Sounds great! Thank you!

I cloned the repo and tried to add it as a temporary extension (in Firefox). I see the option in the context menu, but when I click it the page does not enter reader view.

**Comment by rNeomy** [comment]
Seems like it is not possible to use `document.open` or `document.write` on FF. For now try it on Chrome.

**Comment by alex-rozenshteyn-leapyear** [comment]
Explicitly setting the HTML for `document.head` and `document.body` seems to work in Firefox.
