### ISSUE TITLE
[Request] Greater font control would be awesome

### ISSUE THREAD

**Issue by rv-bnowak** [rNeomy/reader-view#63]
Two things in that regard.
1. The ability to see the font size reflected in the +/- font-size controls. This would be helpful in sizing correctly for printing. Right now it's guess-work.
2. Ability to load custom fonts (maybe from google fonts, or even just a few more than just serif/sans-serif)

Otherwise I love this product.  Keep up the great work!

**Comment by rNeomy** [comment]
> The ability to see the font size reflected in the +/- font-size controls

I'll see if I can find a place for it. Thanks for the report.

> Ability to load custom fonts

Have you tried the custom CSS section? I think you can load fonts too. Read the FAQs page for more info.
