### ISSUE TITLE
Cannot action with mouse

### ISSUE THREAD

**Issue by Contrajur** [rNeomy/reader-view#64]
The app no longer works with the mouse because it now opens a context menu instead.  Since I now can only use it with a shortcut this is not satisfactory because I rely upon my mouse heavily and often do not a keyboard at hand.

**Comment by rNeomy** [comment]
It works for me. What is your browser?

**Comment by leo-smi** [comment]
Isn't working for me too, there is no more the option to "simple view", I think it happend after allow anonimous mode (chrome)
