### ISSUE TITLE
HiDPI Icon in Opera

### ISSUE THREAD

**Issue by ElvisPresly** [rNeomy/reader-view#7]
Hi, whether it is possible to improve quality of an icon in HiDPI (retina) permission?
![default](https://user-images.githubusercontent.com/18265958/30108640-bb1ddbfa-930b-11e7-9c7a-cc58ebb96747.PNG)

**Comment by rNeomy** [comment]
This seems like a bug in the Windows version of Opera.
Normal DPI
![screen shot 2017-09-07 at 9 35 32 am](https://user-images.githubusercontent.com/14104614/30146892-f7c49a0e-93af-11e7-833e-6d176c99a1e4.png)
Retina:
<img width="165" alt="screen shot 2017-09-07 at 9 35 39 am" src="https://user-images.githubusercontent.com/14104614/30146893-f8964ee6-93af-11e7-9fe8-fb85084177a0.png">

Do you have the same issue in Chrome too?

**Comment by ElvisPresly** [comment]
In Chrome looks perfectly.
![default](https://user-images.githubusercontent.com/18265958/30150909-ec41b0b2-93b5-11e7-9bee-211856a26fec.PNG)

**Comment by rNeomy** [comment]
So I guess we need to wait for Opera to fix it. If you have another extension with the correct pixel size, please let me know the link
