### ISSUE TITLE
Reader View does not render mathjax properly

### ISSUE THREAD

**Issue by Bamajon1974** [rNeomy/reader-view#70]
When opening a webpage originally with mathjax equations, the formulas are lost when switching to reader view. Toggling images to show or hide does nothing. How can this issue be resolved? 
Try this sample page
Thanks!

Update...if you install WikiWand extension and go to reader view, the equations are displayed. Why would this happen?

**Comment by Bamajon1974** [comment]
Has this issue been addressed in Chrome and/or Firefox?

**Comment by rNeomy** [comment]
Yes, on version 0.4.1 the math formula are rendered by MathJax

**Comment by Bamajon1974** [comment]
Thank you very much!
