### ISSUE TITLE
Reader-View Extension doesn't capture whole site but Chrome's default viewer does it

### ISSUE THREAD

**Issue by anishmittal2020** [rNeomy/reader-view#75]
- Enable Chrome reader view: `chrome://flags/#enable-reader-mode`
- Go to: <https://dorfbladl.com/de/effective-altruism/>
  - Chrome's default viewer coompletely renders it
  - Reader View only shows first few lines!

**Comment by rNeomy** [comment]
It works fine for me. Are you sure you haven't selected a few lines before pressing the button? This extension only ports the selected area to the reader's view if any found.

**Comment by anishmittal2020** [comment]
You are correct.
