### ISSUE TITLE
urls in Dark mode barely readable.

### ISSUE THREAD

**Issue by archderwelt** [rNeomy/reader-view#8]
urls/links in dark mode are almost unreadable. Plz change it to another color or add option to choose one. It is not the same as in the firefox addon. Thanks 
Screenshot:
https://i.imgur.com/s0LsjYK.png

Mozilla version:
https://i.imgur.com/0f6njiI.png

**Comment by rNeomy** [comment]
Thanks for the report. I'll fix this in the next release.
