### ISSUE TITLE
[Feature Request] Nord theme

### ISSUE THREAD

**Issue by ovigia** [rNeomy/reader-view#85]
Can you please implement a light and dark color mode with the Nord theme colors?

https://www.nordtheme.com/

thank you

**Comment by rNeomy** [comment]
We are going to have two new themes;

![light](https://user-images.githubusercontent.com/14104614/95658029-68735e80-0b07-11eb-86d8-03e4f1494764.png)
![dark](https://user-images.githubusercontent.com/14104614/95658031-6a3d2200-0b07-11eb-88b8-25639b67a294.png)
