### ISSUE TITLE
Ability to enlarge the font size

### ISSUE THREAD

**Issue by TheBlinded** [rNeomy/reader-view#9]
Could you add the ability to further enlarge the font size? I often use the extension to see better but I can not enlarge the size much more...
Thanks!

**Comment by rNeomy** [comment]
Are you using this on FF or Chrome? In Chrome, you can have custom style to enlarge the font-size to whatever level you need! See my comment; https://add0n.com/chrome-reader-view.html#IDComment1056978838

In FF, there is no way as the extension has no control over the internal resource.
