### ISSUE TITLE
Feature request: automatic dark mode on MacOS Catalina+

### ISSUE THREAD

**Issue by antois** [rNeomy/reader-view#92]
Hey there,

First, thanks for the awesome app.

Second, please consider implementing an automatic dark mode depending on OS status. I use automatic dark mode on MacOS Catalina and having this add-on switching automatically from Sepia/White theme to Dark theme when the rest of the system does so would be great (and nice for the eyes). 

All the best!

**Comment by rNeomy** [comment]
Since we don't have an interface for this dual color scheme, I added a new FAQ to use the custom styling section of the options page to achieve it.

Read FAQ #20
https://add0n.com/chrome-reader-view.html?tbp
